version: '3'
services:
  app:
    build: .
    image: weather-clothes
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/project_weather-clothes
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - CHROME_DRIVER_PATH=${CHROME_DRIVER_PATH}
    volumes:
      - C:/Users/k4150/chromedriver/chromedriver-win64/chromedriver.exe:/usr/local/bin/chromedriver
